### ISSUE TITLE
Pulled recent update (d43b257) and can no longer run

### ISSUE THREAD

**Issue by jtvanlew** [gatk-workflows/gatk4-mitochondria-pipeline#4]
I pulled this update and now it seems I can't run the pipeline anymore -- at least running it locally. I get the same error when I use this pipeline with my own inputs or with the example input given in the repo. 

I've been using Cromwell-39 with no issues up to this point.

Here's the error during startup:

> [2019-11-21 16:49:44,97] [error] WorkflowManagerActor Workflow d08331b4-8f5c-4f74-b7f5-595549c40e90 failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
WARNING: Unexpected input provided: #MitochondriaPipeline.ref_dict
WARNING: Unexpected input provided: #MitochondriaPipeline.m2_extra_args
WARNING: Unexpected input provided: #MitochondriaPipeline.f_score_beta
WARNING: Unexpected input provided: #MitochondriaPipeline.m2_filter_extra_args
WARNING: Unexpected input provided: ##_COMMENT3
WARNING: Unexpected input provided: #MitochondriaPipeline.CallAndFilterShiftedMt.M2AndFilter.gga_vcf_idx
WARNING: Unexpected input provided: #MitochondriaPipeline.vaf_filter_threshold
WARNING: Unexpected input provided: #MitochondriaPipeline.CallAndFilterMt.M2AndFilter.make_bamout
WARNING: Unexpected input provided: #MitochondriaPipeline.ref_fasta_index
WARNING: Unexpected input provided: #MitochondriaPipeline.CallAndFilterShiftedMt.M2AndFilter.gga_vcf
WARNING: Unexpected input provided: #MitochondriaPipeline.CallAndFilterShiftedMt.M2AndFilter.make_bamout
WARNING: Unexpected input provided: #MitochondriaPipeline.AlignToMt.AlignAndMarkDuplicates.read_name_regex
WARNING: Unexpected input provided: #MitochondriaPipeline.autosomal_coverage
WARNING: Unexpected input provided: ##_COMMENT2
WARNING: Unexpected input provided: #MitochondriaPipeline.GetContamination.map_qual
WARNING: Unexpected input provided: #MitochondriaPipeline.GetContamination.vaf
WARNING: Unexpected input provided: #MitochondriaPipeline.CoverageAtEveryBase.preemptible_tries
WARNING: Unexpected input provided: #MitochondriaPipeline.CallAndFilterMt.M2AndFilter.gga_vcf
WARNING: Unexpected input provided: ##_COMMENT5
WARNING: Unexpected input provided: ##_COMMENT4
WARNING: Unexpected input provided: #MitochondriaPipeline.preemptible_tries
WARNING: Unexpected input provided: #MitochondriaPipeline.AlignToShiftedMt.AlignAndMarkDuplicates.read_name_regex
WARNING: Unexpected input provided: #MitochondriaPipeline.GetContamination.qual
WARNING: Unexpected input provided: #MitochondriaPipeline.CallAndFilterMt.M2AndFilter.m2_extra_filtering_args
WARNING: Unexpected input provided: ##_COMMENT1
WARNING: Unexpected input provided: #MitochondriaPipeline.CallAndFilterMt.M3AndFilter.gga_vcf_idx
WARNING: Unexpected input provided: #MitochondriaPipeline.gatk_override
WARNING: Unexpected input provided: #MitochondriaPipeline.CallAndFilterShiftedMt.M2AndFilter.m2_extra_filtering_args
WARNING: Unexpected input provided: #MitochondriaPipeline.ref_fasta
WARNING: Unexpected input provided: #MitochondriaPipeline.max_read_length
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:215)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:185)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:180)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by jtvanlew** [comment]
ok it seems that WDL 1 doesn't default allow comments in input files? I'm using all vanilla settings and configurations from Cromwell. I had to create a custom config file and set strict-validation:false and it launched. is that good behavior for this workflow example file?
